[package]
name = "oxplow-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oxplow-domain = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
serde = { workspace = true }
serde_json = { workspace = true }
lsp-types = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
oxplow-workspace-hack = { version = "0.1", path = "../oxplow-workspace-hack" }

[lints]
workspace = true
