[package]
name = "oxplow-ai-providers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oxplow-ai = { workspace = true }
oxplow-domain = { workspace = true }
oxplow-script = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
oxplow-workspace-hack = { version = "0.1", path = "../oxplow-workspace-hack" }

[dev-dependencies]
oxplow-ai-fake = { workspace = true }

[lints]
workspace = true
