//! Tauri command + event adapter.
//!
//! Each `#[tauri::command]` is a thin wrapper around an `oxplow-app`
//! service method. Errors convert at this boundary into the
//! frontend-facing `IpcError`. `tauri-specta` exports the typed JS
//! bindings consumed by `apps/desktop/src/tauri-bridge/`.

pub mod commands;
pub mod error;
pub mod state;
pub mod windows;

pub use error::IpcError;
pub use state::{AppState, PluginRuntime, PluginRuntimeState, RecentProjectsState};

use tauri_specta::{collect_commands, Builder};

pub use oxplow_app::OxplowEvent;

/// Stable event channel name used by the renderer's `listen` calls.
/// Payload is `OxplowEvent` JSON. Sourced from the shared channel
/// registry in `oxplow_app::event_channels`.
pub const OXPLOW_EVENT_CHANNEL: &str = oxplow_app::event_channels::OXPLOW;

/// Commands that legitimately exist only as Tauri adapters and are NOT
/// served by the headless daemon's `oxplow_rpc::dispatch` registry:
/// they need the desktop shell itself (windowing, native menus, the OS
/// clipboard, launching external apps, project/workspace lifecycle
/// before a daemon is even booted). Everything else MUST be in the
/// dispatch registry or it 404s over `POST /ipc/:name`. Keep this list
/// tight — adding a row is an explicit "the daemon can't do this"
/// decision.
///
/// This is the **definition of the shell surface**, and it has two
/// consumers besides the parity test that guards it:
///
/// - the renderer's transport routes these to Tauri IPC and everything
///   else to the window's daemon — the list is generated into
///   `apps/desktop/src/tauri-bridge/generated/shellCommands.ts` by the
///   `export_ts_bindings` test below, so the TS table can't drift;
/// - it is what survives in this crate once the in-process backend is
///   retired (tsk260).
pub const SHELL_ONLY_COMMANDS: &[&str] = &[
    "abort_setup",
    "clipboard_read_text",
    "create_project",
    "list_recent_projects",
    "open_external_url",
    "open_project",
    "remove_recent_project",
    "set_native_menu",
    "setup_project",
];

/// The generated TS module carrying [`SHELL_ONLY_COMMANDS`] to the
/// renderer's transport switch. Written by `export_ts_bindings`; the
/// surface-parity test asserts the file on disk still matches. Test-only
/// for the same reason the bindings export is: generating checked-in
/// source is a build-time job, not something the shipped app does.
#[cfg(test)]
fn shell_commands_module() -> String {
    let mut out = String::from(
        "// GENERATED by `cargo test -p oxplow-tauri-ipc export_ts_bindings` — do not edit.\n\
         //\n\
         // Commands the desktop shell serves itself (windowing, native menus,\n\
         // clipboard, project lifecycle). The transport routes these to Tauri\n\
         // IPC and every other command to this window's daemon. Source of\n\
         // truth: `SHELL_ONLY_COMMANDS` in crates/oxplow-tauri-ipc/src/lib.rs.\n\
         \n\
         export const SHELL_COMMANDS = [\n",
    );
    for name in SHELL_ONLY_COMMANDS {
        out.push_str(&format!("  \"{name}\",\n"));
    }
    out.push_str("] as const;\n");
    out
}

/// Build the tauri-specta `Builder` registering every oxplow command.
/// Also exports `OxplowEvent` itself so the renderer derives its
/// event-kind union from the generated type instead of hand-
/// maintaining one (the "camelcase trap").
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .typ::<OxplowEvent>()
        .commands(collect_commands![
            // app
            commands::generated::app_version,
            commands::generated::ping,
            commands::generated::log_ui,
            // streams
            commands::generated::list_streams,
            commands::generated::create_worktree,
            commands::generated::adopt_worktree,
            commands::generated::archive_stream,
            commands::generated::get_primary_stream,
            commands::generated::get_current_stream,
            commands::generated::switch_stream,
            commands::generated::rename_stream,
            commands::generated::set_stream_prompt,
            commands::generated::checkout_stream_branch,
            commands::generated::reorder_streams,
            // threads
            commands::generated::list_threads,
            commands::generated::create_thread,
            commands::generated::rename_thread,
            commands::generated::set_thread_prompt,
            commands::generated::promote_thread,
            commands::generated::close_thread,
            commands::generated::reopen_thread,
            commands::generated::list_closed_threads,
            commands::generated::reorder_thread_queue,
            commands::generated::select_thread,
            commands::generated::get_thread_state,
            commands::generated::get_thread_work_state,
            // tasks
            commands::generated::get_task,
            commands::generated::upsert_task,
            commands::generated::delete_task,
            commands::generated::create_task,
            commands::generated::update_task,
            commands::generated::reorder_tasks,
            commands::generated::move_task,
            commands::generated::list_dashboards,
            commands::generated::get_dashboard,
            commands::generated::create_dashboard,
            commands::generated::rename_dashboard,
            commands::generated::set_dashboard_settings,
            commands::generated::duplicate_dashboard,
            commands::generated::delete_dashboard,
            commands::generated::add_dashboard_item,
            commands::generated::update_dashboard_item,
            commands::generated::remove_dashboard_item,
            commands::generated::reorder_dashboard_items,
            // backlog
            commands::generated::list_backlog,
            commands::generated::get_backlog_state,
            // search
            commands::generated::search,
            // notes (task / thread)
            commands::generated::add_thread_note,
            commands::generated::list_thread_notes,
            commands::generated::list_task_events,
            // comments
            commands::generated::create_comment,
            commands::generated::add_comment_message,
            commands::generated::list_comments_for_target,
            commands::generated::list_comments_for_stream,
            commands::generated::set_comment_intent,
            commands::generated::set_comment_status,
            commands::generated::set_comment_anchor,
            commands::generated::relink_comment,
            commands::generated::delete_comment,
            // wiki
            commands::generated::list_wiki_pages,
            commands::generated::upsert_wiki_page,
            commands::generated::delete_wiki_page,
            commands::generated::search_wiki_titles,
            commands::generated::read_wiki_page_body,
            commands::generated::write_wiki_page_body,
            // page refs (unified backlinks/outbound)
            commands::generated::list_backlinks,
            commands::generated::list_outbound,
            // wiki freshness (V20 file-ref version tracking)
            commands::generated::list_wiki_freshness,
            commands::generated::mark_wiki_ref_verified,
            commands::generated::mark_all_wiki_refs_verified,
            // page visit
            commands::generated::record_page_visit,
            commands::generated::list_recent_page_visits,
            commands::generated::top_visited_pages,
            commands::generated::forget_page,
            commands::generated::count_page_visits_by_day,
            commands::generated::list_recently_finished,
            commands::generated::clear_recently_finished,
            // usage
            commands::generated::record_usage,
            commands::generated::list_recent_usage_rollup,
            // code quality (duplication only — metrics scan retired, tsk229)
            commands::generated::list_code_quality_findings,
            commands::generated::run_duplication_scan_at,
            commands::generated::find_latest_code_quality_scan,
            commands::generated::analyze_functions_at_refs,
            commands::generated::analyze_co_change_surprise,
            // snapshots
            commands::generated::list_snapshots,
            commands::generated::list_file_snapshots_for_stream,
            commands::generated::list_snapshots_for_stream,
            commands::generated::list_files_for_snapshot,
            commands::generated::list_wiki_slugs_for_snapshots,
            commands::generated::get_snapshot,
            commands::generated::get_snapshot_pair_diff,
            commands::generated::diff_endpoints,
            commands::generated::read_endpoint_files_content,
            commands::generated::get_snapshot_summary,
            commands::generated::get_snapshot_stats,
            commands::generated::list_snapshot_change_entries,
            commands::generated::read_snapshot_file_content,
            commands::generated::get_blob_storage_bytes,
            commands::generated::restore_file_from_snapshot,
            // branch
            commands::generated::list_branches,
            commands::generated::get_default_branch,
            commands::generated::rename_branch,
            commands::generated::delete_branch,
            commands::generated::list_local_branches,
            // git
            commands::generated::get_repo_conflict_state,
            commands::generated::get_ahead_behind,
            commands::generated::list_stream_divergences,
            commands::generated::append_to_gitignore,
            commands::generated::restore_path,
            commands::generated::git_fetch,
            commands::generated::git_pull,
            commands::generated::git_pull_remote_into_current,
            commands::generated::git_push,
            commands::generated::git_push_current_to,
            commands::generated::git_merge_into,
            commands::generated::git_rebase_onto,
            commands::generated::git_cherry_pick,
            commands::generated::git_revert,
            commands::generated::git_commit_all,
            commands::generated::git_add_path,
            commands::generated::list_all_refs,
            commands::generated::resolve_commit_ref_labels,
            commands::generated::list_recent_remote_branches,
            commands::generated::list_file_commits,
            commands::generated::read_file_at_ref,
            commands::generated::search_workspace_text,
            commands::generated::list_adoptable_worktrees,
            commands::generated::git_blame,
            commands::generated::local_blame,
            commands::generated::get_branch_changes,
            commands::generated::get_change_scopes,
            // hooks / agent lifecycle
            commands::generated::ingest_hook_event,
            commands::generated::list_hook_events,
            commands::generated::list_agent_statuses,
            commands::generated::list_open_agent_turns,
            // config
            commands::generated::get_config,
            commands::generated::set_agent_prompt_append,
            commands::generated::set_agents,
            commands::generated::set_snapshot_retention_days,
            commands::generated::set_snapshot_max_file_bytes,
            commands::generated::set_generated,
            commands::generated::set_agent_model,
            commands::generated::get_workspace_context,
            // efforts
            commands::generated::list_task_efforts,
            commands::generated::get_effort_files,
            commands::generated::get_effort,
            commands::generated::list_efforts_at_snapshots,
            commands::generated::list_efforts_overlapping_range,
            commands::generated::list_changed_paths_for_effort,
            commands::generated::list_efforts_in_window,
            commands::generated::list_effort_observations,
            commands::generated::list_effort_metric_deltas,
            commands::generated::list_metric_definitions,
            commands::generated::list_metric_samples,
            commands::generated::metric_dimension_rollup,
            commands::generated::list_metric_findings,
            commands::generated::metric_series,
            commands::generated::metric_rollup,
            commands::generated::list_metric_catalog,
            commands::generated::set_metric_enabled,
            commands::generated::set_metrics_enabled,
            commands::generated::set_metric_override,
            commands::generated::list_nudges_for_effort,
            commands::generated::list_token_usage_for_effort,
            commands::generated::get_effort_token_totals,
            commands::generated::get_thread_token_totals,
            commands::generated::token_totals_overall,
            commands::generated::token_usage_by_agent,
            commands::generated::token_usage_by_model,
            commands::generated::token_usage_by_day,
            // log
            commands::generated::get_git_log,
            commands::generated::get_commit_detail,
            commands::generated::get_commits_ahead_of,
            // workspace
            commands::generated::list_workspace_entries,
            commands::generated::list_workspace_files,
            commands::generated::read_workspace_file,
            commands::generated::read_file,
            commands::generated::write_workspace_file,
            commands::generated::create_workspace_file,
            commands::generated::create_workspace_directory,
            commands::generated::rename_workspace_path,
            commands::generated::delete_workspace_path,
            commands::generated::get_workspace_status_summary,
            // background tasks
            commands::generated::list_background_tasks,
            commands::generated::get_background_task,
            commands::generated::start_background_task,
            commands::generated::complete_background_task,
            commands::generated::fail_background_task,
            commands::generated::update_background_task,
            // followups
            commands::generated::list_followups,
            commands::generated::add_followup,
            commands::generated::remove_followup,
            // webview
            commands::webview::open_external_url,
            commands::webview::clipboard_read_text,
            // lsp
            commands::generated::install_lsp_package,
            commands::generated::list_installed_lsp_packages,
            commands::generated::lsp_request,
            commands::generated::lsp_notify,
            commands::generated::list_lsp_servers,
            commands::generated::restart_lsp_server,
            commands::generated::remove_lsp_package,
            commands::generated::respond_lsp_apply_edit,
            // terminal
            commands::terminal::open_terminal_session,
            commands::generated::forward_terminal_input,
            commands::generated::close_terminal_session,
            commands::generated::terminal_session_cwd,
            commands::generated::terminate_terminal_session,
            commands::generated::lookup_terminal_session,
            // menu
            commands::menu::set_native_menu,
            // launcher / multi-window
            commands::launch::list_recent_projects,
            commands::launch::remove_recent_project,
            commands::launch::open_project,
            commands::launch::create_project,
            commands::launch::setup_project,
            commands::launch::abort_setup,
        ])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Smoke test: the builder constructs without panicking.
    #[test]
    fn builder_constructs() {
        let _b = specta_builder();
    }

    /// Regenerate the TS bindings file the frontend imports.
    /// CI fails if `git diff` is non-empty after `cargo test`.
    #[test]
    fn export_ts_bindings() {
        let manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
            Ok(v) => v,
            Err(_) => return,
        };
        let workspace_root = std::path::Path::new(&manifest_dir)
            .parent()
            .and_then(|p| p.parent())
            .expect("workspace root");
        let target = workspace_root.join("apps/desktop/src/tauri-bridge/generated/bindings.ts");
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).expect("create bridge dir");
        }
        let builder = specta_builder();
        builder
            .export(specta_typescript::Typescript::default(), &target)
            .expect("export bindings");
        // Route every generated invoke through the transport switch so
        // remote mode (fetch to the daemon) works without touching the
        // ~130 call sites. tauri-specta has no hook for the import
        // path, so rewrite it post-export; local mode is unchanged
        // because ../transport delegates to @tauri-apps/api/core.
        let generated = std::fs::read_to_string(&target).expect("read bindings");
        let routed = generated.replace(
            "import { invoke as __TAURI_INVOKE } from \"@tauri-apps/api/core\";",
            "import { invoke as __TAURI_INVOKE } from \"../transport\";",
        );
        assert!(
            routed.contains("from \"../transport\""),
            "expected to rewrite the bindings' invoke import; did tauri-specta change its header?"
        );
        std::fs::write(&target, routed).expect("write routed bindings");
        let metadata = std::fs::metadata(&target).expect("bindings written");
        assert!(metadata.len() > 0, "bindings file should not be empty");

        // The transport's routing table, emitted from the Rust
        // definition so it can't drift (the surface-parity test asserts
        // the file on disk still matches).
        let shell_commands = target
            .parent()
            .expect("generated dir")
            .join("shellCommands.ts");
        std::fs::write(&shell_commands, shell_commands_module()).expect("write shell commands");
    }

    #[test]
    fn shell_commands_module_is_a_valid_ts_string_array() {
        let module = shell_commands_module();
        assert!(module.contains("export const SHELL_COMMANDS = ["));
        assert!(module.contains("] as const;"));
        for name in SHELL_ONLY_COMMANDS {
            assert!(
                module.contains(&format!("\"{name}\",")),
                "{name} missing from the generated module"
            );
        }
    }

    /// Command names are plain identifiers; anything else would need
    /// escaping in the generated TS and this guard would be the place
    /// it's noticed.
    #[test]
    fn shell_only_commands_need_no_ts_escaping() {
        for name in SHELL_ONLY_COMMANDS {
            assert!(
                name.bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'.'),
                "{name} is not a bare command name"
            );
        }
    }
}
