//! Tauri command + event adapter.
//!
//! Each `#[tauri::command]` is a thin wrapper around an `oxplow-app`
//! service method. Errors convert at this boundary into the
//! frontend-facing `IpcError`. `tauri-specta` exports the typed JS
//! bindings consumed by `apps/desktop/src/tauri-bridge/`.

pub mod commands;
pub mod error;
pub mod state;
pub mod windows;

pub use error::IpcError;
pub use state::{AppState, PluginRuntime, PluginRuntimeState, RecentProjectsState};

use tauri_specta::{collect_commands, Builder};

pub use oxplow_app::OxplowEvent;

/// Stable event channel name used by the renderer's `listen` calls.
/// Payload is `OxplowEvent` JSON. Sourced from the shared channel
/// registry in `oxplow_app::event_channels`.
pub const OXPLOW_EVENT_CHANNEL: &str = oxplow_app::event_channels::OXPLOW;

/// Commands that legitimately exist only as Tauri adapters and are NOT
/// served by the headless daemon's `oxplow_rpc::dispatch` registry:
/// they need the desktop shell itself (windowing, native menus, the OS
/// clipboard, launching external apps, project/workspace lifecycle
/// before a daemon is even booted). Everything else MUST be in the
/// dispatch registry or it 404s over `POST /ipc/:name`. Keep this list
/// tight — adding a row is an explicit "the daemon can't do this"
/// decision.
///
/// This is the **definition of the shell surface**, and it has two
/// consumers besides the parity test that guards it:
///
/// - the renderer's transport routes these to Tauri IPC and everything
///   else to the window's daemon — the list is generated into
///   `apps/desktop/src/tauri-bridge/generated/shellCommands.ts` by the
///   `export_ts_bindings` test below, so the TS table can't drift;
/// - it is what survives in this crate once the in-process backend is
///   retired (tsk260).
pub const SHELL_ONLY_COMMANDS: &[&str] = &[
    "abort_setup",
    "answer_oauth_redirect",
    "await_oauth_redirect",
    "clipboard_read_text",
    "create_project",
    "list_recent_projects",
    "listen_for_oauth_redirect",
    "open_external_url",
    "open_project",
    "remove_recent_project",
    "set_native_menu",
    "setup_project",
    "stop_oauth_redirect",
];

/// The generated TS module carrying [`SHELL_ONLY_COMMANDS`] to the
/// renderer's transport switch. Written by `export_ts_bindings`; the
/// surface-parity test asserts the file on disk still matches. Test-only
/// for the same reason the bindings export is: generating checked-in
/// source is a build-time job, not something the shipped app does.
#[cfg(test)]
fn shell_commands_module() -> String {
    let mut out = String::from(
        "// GENERATED by `cargo test -p oxplow-tauri-ipc export_ts_bindings` — do not edit.\n\
         //\n\
         // Commands the desktop shell serves itself (windowing, native menus,\n\
         // clipboard, project lifecycle). The transport routes these to Tauri\n\
         // IPC and every other command to this window's daemon. Source of\n\
         // truth: `SHELL_ONLY_COMMANDS` in crates/oxplow-tauri-ipc/src/lib.rs.\n\
         \n\
         export const SHELL_COMMANDS = [\n",
    );
    for name in SHELL_ONLY_COMMANDS {
        out.push_str(&format!("  \"{name}\",\n"));
    }
    out.push_str("] as const;\n");
    out
}

/// Build the tauri-specta `Builder` registering every oxplow command.
/// Also exports `OxplowEvent` itself so the renderer derives its
/// event-kind union from the generated type instead of hand-
/// maintaining one (the "camelcase trap"), `AcpEvent` (the
/// `acp:event` payload) for the same reason, and `OpOutcome` — what the
/// `vcs.*` / `git.*` bus commands return, which no RPC names.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .typ::<OxplowEvent>()
        .typ::<oxplow_app::acp::session::AcpEvent>()
        .typ::<oxplow_domain::vcs::OpOutcome>()
        // A provider's work-item flags (`v_capability_provider.features`).
        .typ::<oxplow_domain::work_items::WorkItemsFeatures>()
        // `collector.sync`'s result, read through `run_command`.
        .typ::<oxplow_app::collector_runner::CollectorRunReport>()
        // What `lens.keep` keeps from Explore Data's Save as Lens.
        .typ::<oxplow_app::extensions::LensSpec>()
        .commands(collect_commands![
            // app
            commands::generated::app_version,
            commands::generated::ping,
            commands::generated::log_ui,
            // streams
            commands::generated::list_streams,
            commands::generated::get_primary_stream,
            commands::generated::get_current_stream,
            commands::generated::switch_stream,
            // threads
            commands::generated::list_threads,
            commands::generated::list_acp_agents,
            commands::generated::list_closed_threads,
            commands::generated::select_thread,
            commands::generated::get_thread_state,
            // tasks
            commands::generated::list_dashboards,
            commands::generated::get_dashboard,
            // backlog
            // search
            commands::generated::search,
            // semantic layer
            commands::generated::query_sql,
            commands::generated::list_data_entities,
            commands::generated::prompt_catalog,
            commands::generated::effective_config,
            commands::generated::get_panel_layout,
            commands::generated::set_panel_layout,
            // extensions + lenses
            commands::generated::list_extensions,
            commands::generated::get_lens,
            commands::generated::run_lens,
            commands::generated::run_lens_action,
            commands::generated::lens_text,
            commands::generated::run_answer,
            commands::generated::lens_form,
            commands::generated::submit_lens_form,
            commands::generated::run_component_query,
            commands::generated::invoke_component_command,
            commands::generated::validate_extension,
            commands::generated::review_extension,
            commands::generated::report_open_page,
            commands::generated::set_extension_enabled,
            commands::generated::list_collectors,
            commands::generated::approve_collector,
            commands::generated::set_credential,
            commands::generated::list_project_programs,
            commands::generated::approve_project_program,
            commands::generated::program_source,
            commands::generated::provider_declaration_effects,
            commands::generated::list_provider_instances,
            commands::generated::check_provider_instance,
            commands::generated::set_provider_instance,
            commands::generated::add_provider_instance,
            commands::generated::remove_provider_instance,
            commands::generated::turn_off_provider_instance_here,
            commands::generated::set_instance_credential,
            commands::generated::begin_oauth_sign_in,
            commands::generated::cancel_oauth_sign_in,
            commands::generated::complete_oauth_sign_in,
            // The sign-in redirect, caught by the shell (P10).
            commands::oauth_redirect::listen_for_oauth_redirect,
            commands::oauth_redirect::await_oauth_redirect,
            commands::oauth_redirect::answer_oauth_redirect,
            commands::oauth_redirect::stop_oauth_redirect,
            commands::generated::ensure_change,
            commands::generated::ai_settings,
            commands::generated::save_ai_provider,
            commands::generated::remove_ai_provider,
            commands::generated::set_ai_role,
            commands::generated::test_ai_provider,
            // notes (task / thread)
            commands::generated::list_thread_notes,
            // comments
            commands::generated::list_comments_for_target,
            commands::generated::list_comments_for_stream,
            // wiki
            // events (dead-letter queue)
            commands::generated::list_dead_letters,
            commands::generated::retry_dead_letter,
            commands::generated::discard_dead_letter,
            // page refs (unified backlinks/outbound)
            commands::generated::list_backlinks,
            commands::generated::list_outbound,
            // wiki freshness (V20 file-ref version tracking)
            // page visit
            commands::generated::record_page_visit,
            commands::generated::list_recent_page_visits,
            commands::generated::top_visited_pages,
            commands::generated::forget_page,
            // usage
            commands::generated::record_usage,
            commands::generated::list_recent_usage_rollup,
            // code quality (duplication only — metrics scan retired, tsk229)
            // snapshots
            commands::generated::list_file_snapshots,
            commands::generated::list_snapshots_for_stream,
            commands::generated::list_snapshot_ops,
            commands::generated::list_files_for_snapshot,
            commands::generated::list_wiki_slugs_for_snapshots,
            commands::generated::get_file_snapshot,
            commands::generated::diff,
            commands::generated::extension_effects_between,
            commands::generated::get_snapshot_stats,
            commands::generated::get_blob_storage_bytes,
            // branch
            // git
            commands::generated::git_resolve_commit_ref_labels,
            commands::generated::git_list_recent_remote_branches,
            commands::generated::read_at,
            commands::generated::search_workspace_text,
            commands::generated::git_change_scopes,
            // hooks / agent lifecycle
            commands::generated::ingest_hook_event,
            commands::generated::list_agent_events,
            commands::generated::read_event_content,
            commands::generated::list_agent_statuses,
            commands::generated::list_open_agent_turns,
            commands::generated::get_agent_turn,
            // config
            commands::generated::get_config,
            commands::generated::set_agent_prompt_append,
            commands::generated::set_agents,
            commands::generated::set_generated,
            commands::generated::set_agent_model,
            commands::generated::get_workspace_context,
            // efforts
            commands::generated::get_effort_files,
            commands::generated::get_effort,
            commands::generated::list_efforts_at_snapshots,
            commands::generated::list_efforts_overlapping_range,
            commands::generated::list_changed_paths_for_effort,
            commands::generated::list_efforts_in_window,
            commands::generated::enable_metrics,
            commands::generated::run_command,
            commands::generated::get_command,
            commands::generated::undo_command,
            commands::generated::decide_proposal,
            // log
            // workspace
            commands::generated::list_workspace_entries,
            commands::generated::list_workspace_files,
            commands::generated::read_workspace_file,
            commands::generated::files_at,
            commands::generated::vcs_head,
            commands::generated::vcs_status,
            commands::generated::vcs_blame,
            commands::generated::vcs_revision,
            commands::generated::vcs_merge_base,
            commands::generated::vcs_log,
            commands::generated::vcs_branches,
            commands::generated::vcs_divergence,
            commands::generated::vcs_revisions_between,
            commands::generated::vcs_file_history,
            commands::generated::vcs_list_adoptable_workspaces,
            commands::generated::write_workspace_file,
            commands::generated::create_workspace_file,
            commands::generated::create_workspace_directory,
            commands::generated::rename_workspace_path,
            commands::generated::delete_workspace_path,
            // background tasks
            commands::generated::list_background_tasks,
            commands::generated::get_background_task,
            commands::generated::start_background_task,
            commands::generated::complete_background_task,
            commands::generated::fail_background_task,
            commands::generated::update_background_task,
            // followups
            commands::generated::list_followups,
            commands::generated::add_followup,
            commands::generated::remove_followup,
            // webview
            commands::webview::open_external_url,
            commands::webview::clipboard_read_text,
            // lsp
            commands::generated::list_installed_lsp_packages,
            commands::generated::lsp_request,
            commands::generated::lsp_notify,
            commands::generated::list_lsp_servers,
            commands::generated::restart_lsp_server,
            commands::generated::respond_lsp_apply_edit,
            // terminal
            commands::terminal::open_terminal_session,
            // acp
            commands::terminal::acp_open_session,
            commands::generated::acp_prompt,
            commands::generated::acp_cancel,
            commands::generated::acp_respond_permission,
            commands::generated::acp_transcript,
            commands::generated::acp_dismiss_directive,
            commands::generated::acp_close_session,
            commands::generated::forward_terminal_input,
            commands::generated::close_terminal_session,
            commands::generated::terminal_session_cwd,
            commands::generated::terminate_terminal_session,
            commands::generated::lookup_terminal_session,
            // menu
            commands::menu::set_native_menu,
            // launcher / multi-window
            commands::launch::list_recent_projects,
            commands::launch::remove_recent_project,
            commands::launch::open_project,
            commands::launch::create_project,
            commands::launch::setup_project,
            commands::launch::abort_setup,
        ])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Smoke test: the builder constructs without panicking.
    #[test]
    fn builder_constructs() {
        let _b = specta_builder();
    }

    /// Regenerate the TS bindings file the frontend imports.
    /// CI fails if `git diff` is non-empty after `cargo test`.
    #[test]
    fn export_ts_bindings() {
        let manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
            Ok(v) => v,
            Err(_) => return,
        };
        let workspace_root = std::path::Path::new(&manifest_dir)
            .parent()
            .and_then(|p| p.parent())
            .expect("workspace root");
        let target = workspace_root.join("apps/desktop/src/tauri-bridge/generated/bindings.ts");
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).expect("create bridge dir");
        }
        let builder = specta_builder();
        builder
            .export(specta_typescript::Typescript::default(), &target)
            .expect("export bindings");
        // Route every generated invoke through the transport switch so
        // remote mode (fetch to the daemon) works without touching the
        // ~130 call sites. tauri-specta has no hook for the import
        // path, so rewrite it post-export; local mode is unchanged
        // because ../transport delegates to @tauri-apps/api/core.
        let generated = std::fs::read_to_string(&target).expect("read bindings");
        let routed = generated.replace(
            "import { invoke as __TAURI_INVOKE } from \"@tauri-apps/api/core\";",
            "import { invoke as __TAURI_INVOKE } from \"../transport\";",
        );
        assert!(
            routed.contains("from \"../transport\""),
            "expected to rewrite the bindings' invoke import; did tauri-specta change its header?"
        );
        std::fs::write(&target, routed).expect("write routed bindings");
        let metadata = std::fs::metadata(&target).expect("bindings written");
        assert!(metadata.len() > 0, "bindings file should not be empty");

        // The transport's routing table, emitted from the Rust
        // definition so it can't drift (the surface-parity test asserts
        // the file on disk still matches).
        let shell_commands = target
            .parent()
            .expect("generated dir")
            .join("shellCommands.ts");
        std::fs::write(&shell_commands, shell_commands_module()).expect("write shell commands");
    }

    #[test]
    fn shell_commands_module_is_a_valid_ts_string_array() {
        let module = shell_commands_module();
        assert!(module.contains("export const SHELL_COMMANDS = ["));
        assert!(module.contains("] as const;"));
        for name in SHELL_ONLY_COMMANDS {
            assert!(
                module.contains(&format!("\"{name}\",")),
                "{name} missing from the generated module"
            );
        }
    }

    /// Command names are plain identifiers; anything else would need
    /// escaping in the generated TS and this guard would be the place
    /// it's noticed.
    #[test]
    fn shell_only_commands_need_no_ts_escaping() {
        for name in SHELL_ONLY_COMMANDS {
            assert!(
                name.bytes()
                    .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'.'),
                "{name} is not a bare command name"
            );
        }
    }
}
