[package]
name = "oxplow-harnesses"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
oxplow-domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
oxplow-workspace-hack = { version = "0.1", path = "../oxplow-workspace-hack" }

[dev-dependencies]
oxplow-agent-text = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
